repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.5.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 20.8b0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
